project_identifier: PROJECT_IDENTIFIER_CROWDIN
api_key: API_KEY_CROWDIN
base_path: ./
preserve_hierarchy: true
files:
  - source: /src/en/components/*.js
    translation: /src/%two_letters_code%/components/%original_file_name%
    update_option: "update_as_unapproved"
  - source: /src/en/data/*.js
    translation: /src/%two_letters_code%/data/%original_file_name%
    update_option: "update_as_unapproved"
  - source: /src/en/pages/team.js
    translation: /src/%two_letters_code%/pages/%original_file_name%
    update_option: "update_as_unapproved"
  - source: /src/en/pages/index.js
    translation: /src/%two_letters_code/pages/%original_file_name%
    update_option: "update_as_unapproved"
