project_identifier: PROJECT_IDENTIFIER_CROWDIN
api_key: API_KEY_CROWDIN
base_path: ./
preserve_hierarchy: true
files:
  - source: /src/en/components.po
    translation: /src/%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
  - source: /src/en/data.po
    translation: /src/%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
  - source: /src/en/pages.po
    translation: /src/%two_letters_code%/%original_file_name%
    update_option: update_as_unapproved
