name: Sync Content
on:
  # schedule:
  #   - cron: '0 5 * * *'  # Daily at 5 am
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Xarray Content
        uses: Scientific-Python-Translations/content-sync@main
        with:
          source-repo: "xarray-contrib/xarray.dev"
          source-path: "content/en/"
          source-ref: "main"
          translations-repo: "Scientific-Python-Translations/xarray-translations"
          translations-path: "content/"
          translations-source-path: "content/en/"
          translations-ref: "main"
          auto-merge: "false"
          # These are provided by the Scientific Python Project and allow
          # automation with bots
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          token: ${{ secrets.TOKEN }}
