name: Sync Translations
on:
  #schedule:
  #  - cron: '0 12 * * MON'  # Every Monday at noon
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Xarray translations
        uses: Scientific-Python-Translations/translations-sync@main
        with:
          # Provided by user
          crowdin-project: "Xarray"
          source-repo: "xarray-contrib/xarray.dev"
          source-path: "src/locales/en/"
          source-ref: "main"
          translations-repo: "Scientific-Python-Translations/xarray-website-translations"
          translations-path: "src/locales/"
          translations-source-path: "src/locales/en/"
          translations-ref: "main"
          translation-percentage: "90"
          approval-percentage: "0"
          use-precommit: "flase"
          create-toml-file: "false"
          create-upstream-pr: "false"
          auto-merge: "false"
          # These are provided by the Scientific Python Project and allow
          # automation with bots
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          token: ${{ secrets.TOKEN }}
          crowdin-token: ${{ secrets.CROWDIN_TOKEN }}
